[build]
baseURL="www.tuckerwray.com"
functions= "./functions"
[[redirects]]
from = "/aws"
to = "https://www.credly.com/badges/6a8a62b7-979c-4f3a-a330-ed0bba2ccc31/linked_in_profile"
status = 301
