[build]
baseURL="www.tuckerwray.com"
functions= "./functions"

[[redirects]]
from = "/lambda"
to = "https://www.credly.com/badges/9ddc5207-5a9b-4117-a632-8e966adaf2d3/linked_in_profile"
status = 301

from = "/aws"
to = "https://www.credly.com/badges/6a8a62b7-979c-4f3a-a330-ed0bba2ccc31/linked_in_profile"
status = 301

from = "/sql"
to = "https://verify.w3schools.com/1PIS8VXHQE"
status = 301

from = "/github"
to = "https://github.com/jtwray"
status = 301
